### ISSUE TITLE
[Bug] Mentor App, mentors can't add to their bio

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1-issues#1]
2 mentors complained that they couldn't input bio info.

One said when he clicked save it wouldn't "stick"
Other said it would only stick if he input one field, then saved, then another field, then saved, etc.

**Comment by greenido** [comment]
We need their name/date and next time - try to take a screen shot and/or ping me so we could reproduce it.

**Comment by joshyellin** [comment]
Wqs reporting on behalf of a mentor. He just told me that it was happening
to him the night before so I resolved for him in the admin app. That's all
I know. Mentor was mark Connelly.

Will def take screenshots when I find any bugs.

**Comment by greenido** [comment]
Without detailed steps to reproduce - We can't do anything...
Thx.
