### ISSUE TITLE
[Startups] Missing Logo - Jurnal

### ISSUE THREAD

**Issue by carraresi** [greenido/lpa-1-issues#12]
<img width="702" alt="screen shot 2017-01-18 at 5 15 06 pm" src="https://cloud.githubusercontent.com/assets/18234621/22079082/b96f61fe-dda1-11e6-9c3c-4a28f993ba66.png">

**Comment by greenido** [comment]
You need to make sure that in the admin app we have the link to the logo with https and not http!
e.g. https://services.google.com/fh/files/misc/qluelogotobeused.png
