### ISSUE TITLE
[Mentors] Twitter/URL

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#14]
Noticed that the fields of Twitter and Personal URL, if added do not show up on the Mentor Card on the App. 

<img width="766" alt="screen shot 2017-01-18 at 5 20 16 pm" src="https://cloud.githubusercontent.com/assets/6896507/22079286/67257716-dda2-11e6-837e-fbabb6d7c09f.png">

**Comment by greenido** [comment]
Fixed - please check it and close if it's fine.
