### ISSUE TITLE
[Home] Bootcamp link is outdated

### ISSUE THREAD

**Issue by alyssamaharani** [greenido/lpa-1-issues#15]
Bootcamp link at the bottom of the page still goes to Bootcamp 2.

![screen shot 2017-01-19 at 5 36 24 pm](https://cloud.githubusercontent.com/assets/16075893/22101292/d2edd846-de6d-11e6-911e-ad6bc6f39cef.png)

![screen shot 2017-01-19 at 5 37 55 pm](https://cloud.githubusercontent.com/assets/16075893/22101351/09221e5e-de6e-11e6-927b-686666b43b7f.png)

**Comment by greenido** [comment]
Yep - let's remove it for now.
