### ISSUE TITLE
[Startup] Saved Note doesn't close

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#19]
When saving a note, the note doesn't collapse.  (Caveat logged in for StartUp / Personal Account as part of Dogfood) 

<img width="411" alt="screen shot 2017-01-23 at 4 16 23 pm" src="https://cloud.githubusercontent.com/assets/6896507/22216812/b110d986-e187-11e6-856b-ef851896fbfb.png">

**Comment by greenido** [comment]
Could you please open chrome dev tools (right click and click on 'inspect') and upload a screenshot of the 'console'? It might show me some errors as I can't reproduce it.

**Comment by greenido** [comment]
Fixed. Please confirm and close.
