### ISSUE TITLE
[Mentor] Can't log in

### ISSUE THREAD

**Issue by joshyellin** [greenido/lpa-1-issues#2]
I am unable to log in, despite being whitelisted. Nothing happens when I click "sign in" (pictured below). I also tried all possible "sign in" links (menu, center of screen, and bottom of screen), and am signed into the whitelisted gmail address.

<img width="953" alt="screen shot 2017-01-18 at 12 38 04 am" src="https://cloud.githubusercontent.com/assets/18670546/22056742/6a00d1b0-dd16-11e6-9cb6-e232e4d1ff9c.png">

**Comment by greenido** [comment]
It's fixed.
