### ISSUE TITLE
Adding explanations to the mentoring questions

### ISSUE THREAD

**Issue by melinanina** [greenido/lpa-1-issues#20]
As discussed, please change the mentoring notes questions to:
- What was discussed today in 1-2 sentences? Focus on primary purpose/challenge.
- What was the outcome of the conversation? Focus on solutions and action items.

**Comment by greenido** [comment]
The questions stay.
You are talking here about the explanation text.
For the first one - we want more than 1-2 sentences.

For the 2nd one - no need to tell them to focus on AI - this is the question. We should come up with a better way to explain them what we wish to see in the answer.
