### ISSUE TITLE
[StartUp] - Picture Notes

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#3]
No problem in uploading pictures to "Notes", however when trying to look at that picture in the Startup Notes, there is no picture attached to that specific note. 

<img width="415" alt="screen shot 2017-01-18 at 4 41 56 pm" src="https://cloud.githubusercontent.com/assets/6896507/22077864/17fe4d3e-dd9d-11e6-86a6-e48682560dd1.png">
<img width="416" alt="screen shot 2017-01-18 at 4 42 09 pm" src="https://cloud.githubusercontent.com/assets/6896507/22077865/18080720-dd9d-11e6-82c8-cc6678c827ae.png">

**Comment by greenido** [comment]
Fixed - please confirm.

**Comment by sebarod** [comment]
Works in the new UI. Good to go.

**Comment by greenido** [comment]
Great - please close this issue :)
