### ISSUE TITLE
[Startups] Logos, Re-sizing and Format

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#6]
Logos seem to be different sizes and shapes across the list. 

<img width="803" alt="screen shot 2017-01-18 at 4 54 28 pm" src="https://cloud.githubusercontent.com/assets/6896507/22078335/cbb001c8-dd9e-11e6-88f5-3a970cbd19b8.png">

**Comment by sebarod** [comment]
This doesn't happen in new UI. Nice! 

<img width="415" alt="screen shot 2017-01-23 at 3 42 31 pm" src="https://cloud.githubusercontent.com/assets/6896507/22215455/9d4ffb5c-e182-11e6-9b06-50faade1690b.png">

**Comment by greenido** [comment]
Fixed in the old app as well
