### ISSUE TITLE
[Menu] Different Menu UIs/Options 

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#7]
Rodrigo and I, are looking at different UIs.  (Is this connected to Authorizations, or just a Bug)

Mine:
<img width="1183" alt="screen shot 2017-01-18 at 4 57 05 pm" src="https://cloud.githubusercontent.com/assets/6896507/22078463/29b394e2-dd9f-11e6-8cc2-1b5a22099a6d.png">

**Comment by carraresi** [comment]
Mine:

![menu](https://cloud.githubusercontent.com/assets/18234621/22078481/3aab7c06-dd9f-11e6-8997-8c92d725485d.png)

**Comment by sebarod** [comment]
**Solved** Link used by Seba is Mentor, Rod was Admin (main root url)
