### ISSUE TITLE
[Home] No Icon for Home Icon

### ISSUE THREAD

**Issue by sebarod** [greenido/lpa-1-issues#8]
<img width="417" alt="screen shot 2017-01-18 at 4 20 49 pm" src="https://cloud.githubusercontent.com/assets/6896507/22078698/1142d75a-dda0-11e6-8ed7-e915a52572a9.png">

**Comment by greenido** [comment]
Fixed. Please check it and close.

**Comment by sebarod** [comment]
Trying to re-created under the new UX. Not appearing. @greenido

**Comment by greenido** [comment]
Try with incognito window...
